Repository bowtie-co/atomic-angular-demo, pull requests merged in 2019-05, with the labels that each got.

#3 Polish
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/atoms/btn/btn.component.html
  src/app/atoms/btn/btn.component.scss
  src/app/atoms/btn/btn.component.spec.ts
  src/app/atoms/btn/btn.component.ts
  src/app/atoms/heading/heading.component.html
  src/app/atoms/heading/heading.component.scss
  src/app/atoms/heading/heading.component.spec.ts
  src/app/atoms/heading/heading.component.ts
  src/app/atoms/index.ts
  src/app/atoms/top-racer-card/top-racer-card.component.html
  src/app/atoms/top-racer-card/top-racer-card.component.scss
  src/app/atoms/top-racer-card/top-racer-card.component.spec.ts
  src/app/atoms/top-racer-card/top-racer-card.component.ts
  src/app/ecosystems/dashboard/dashboard.component.html
  src/app/ecosystems/index.ts
  src/app/ecosystems/racer-detail/racer-detail.component.html
  src/app/ecosystems/racer-detail/racer-detail.component.scss
  src/app/ecosystems/racer-detail/racer-detail.component.spec.ts
  src/app/ecosystems/racer-detail/racer-detail.component.ts
  src/app/ecosystems/racers/racers.component.html
  src/app/ecosystems/racers/racers.component.ts
  src/app/ecosystems/results/results.component.html
  src/app/ecosystems/results/results.component.ts
  src/app/molecules/index.ts
  src/app/organisms/index.ts
  src/app/organisms/messages/messages.component.html
  src/app/organisms/table/table.component.html
  src/app/organisms/table/table.component.scss
  src/app/organisms/table/table.component.spec.ts
  src/app/organisms/table/table.component.ts
Labels: enhancement

#5 Load table after creating result
  src/app/ecosystems/results/results.component.ts
Labels: bug

#7 Updates for makefile and test style declaration
  Makefile
  angular.json
Labels: bug, enhancement

#8 Update readme
  README.md
  bin/pre-push
  docker-compose.yml
Labels: enhancement

#10 Fix linting, linting tests are now passing.
  bin/pre-push
  build.sh
  src/app/app-routing.module.ts
  src/app/app.component.spec.ts
  src/app/app.declarations.ts
  src/app/app.imports.ts
  src/app/app.module.ts
  src/app/atoms/btn/btn.component.spec.ts
  src/app/atoms/btn/btn.component.ts
  src/app/atoms/heading/heading.component.spec.ts
  src/app/atoms/heading/heading.component.ts
  src/app/atoms/index.ts
  src/app/atoms/logo/logo.component.spec.ts
  src/app/atoms/nav-link/nav-link.component.spec.ts
  src/app/atoms/nav-link/nav-link.component.ts
  src/app/atoms/top-racer-card/top-racer-card.component.ts
  src/app/classes/racer.ts
  src/app/classes/result.ts
  src/app/ecosystems/dashboard/dashboard.component.ts
  src/app/ecosystems/index.ts
  src/app/ecosystems/racer-detail/racer-detail.component.ts
  src/app/ecosystems/racers/racers.component.ts
  src/app/ecosystems/results/results.component.ts
  src/app/molecules/index.ts
  src/app/molecules/nav-link-group/nav-link-group.component.spec.ts
  src/app/molecules/nav-link-group/nav-link-group.component.ts
  src/app/molecules/racer-search/racer-search.component.spec.ts
  src/app/molecules/racer-search/racer-search.component.ts
  src/app/organisms/index.ts
  src/app/organisms/messages/messages.component.spec.ts
  src/app/organisms/messages/messages.component.ts
  src/app/organisms/navbar/navbar.component.spec.ts
  src/app/organisms/table/table.component.ts
  src/app/services/InMemoryData/in-memory-data.service.ts
  src/app/services/message/message.service.ts
  src/app/services/racer/racer.service.spec.ts
  src/app/services/racer/racer.service.ts
  src/app/services/result/result.service.spec.ts
  src/app/services/result/result.service.ts
Labels: enhancement
